language: php

php:
  - 5.5

script: phpunit Test.php

env:
  global:
    - "FTP_USER=u89720756-arturo"
    - "FTP_PASSWORD=Arturo_09"

after_success:
- if [[ $TRAVIS_BRANCH = "master" ]]; then find application/ assets/ system/ -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://home687786128.1and1-data.host/ else echo 'branch develop'; fi
find web-celebration/ -type f -exec curl -u u89720756-arturo:Arturo_09 --ftp-create-dirs -T {} ftp://home687786128.1and1-data.host/