language: php

php:
  - 7

script: phpunit Test.php

env:
  global:
    - "FTP_USER=u89720756-arturo"
    - "FTP_PASSWORD=Arturo_09"

after_success:
  - if [[ $TRAVIS_BRANCH = "master ]]; then php -f build.php; fi

