language: php

php:
  - 5.5

script: phpunit Test.php

env:
  global:
    - "FTP_USER=u89720756-arturo"
    - "FTP_PASSWORD=Arturo_09"

after_success:
- if [[ $TRAVIS_BRANCH = "master" ]]; then "find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://home687786128.1and1-data.host/{} \;" else echo 'branch develop'; fi